trigger:
  branches:
    include:
      - develop
      - ppe
      - prod

pr:
  branches:
    include:
      - develop

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      python -m pip install -r requirements.txt
      python -m pytest
    displayName: Run tests
