targets:
  prod:
    mode: production
    # Git branch main is the prod branch. This target stays named prod.
    # Same Databricks host as develop for now. Replace this host when prod has its own workspace.
    workspace:
      host: https://adb-7405619226406985.5.azuredatabricks.net
      root_path: /Shared/.bundle/${bundle.name}/${bundle.target}
    variables:
      env: prod
      git_branch: main
      env_suffix: prod
      service_principal_application_id: 25f77508-651e-496b-acfd-0b8f8525162d
