resources:
  jobs:
    iris-infer-script-serverless:
      name: iris-infer-script-serverless
      tags:
        project: iris-ml
        env: develop
        task: infer
        compute: serverless
        managed-by: dab
        owner: ${var.owner}
      tasks:
        - task_key: infer_script
          spark_python_task:
            python_file: ../../notebooks/infer.py
            parameters:
              - --model-uri
              - models:/${var.registered_model_name}
              - --tracking-uri
              - databricks
          environment_key: default
      environments:
        - environment_key: default
          spec:
            client: "2"
            dependencies:
              - ../../requirements-serving.txt
