resources:
  jobs:
    iris-infer-script-serverless:
      name: ${var.env_prefix}-iris-infer-script-serverless
      tags:
        project: iris-ml
        env: ${var.env}
        stage: ${var.env}
        alias: ${var.model_alias}
        task: infer
        compute: serverless
        managed-by: dab
        owner: ${var.owner}
      tasks:
        - task_key: infer_script
          spark_python_task:
            python_file: ../../notebooks/infer.py
            parameters:
              - --model-uri
              - models:/${var.registered_model_name}@${var.model_alias}
              - --tracking-uri
              - databricks
              - --alias
              - ${var.model_alias}
          environment_key: default
      environments:
        - environment_key: default
          spec:
            client: "2"
            dependencies:
              - "-r ../../requirements-serving.txt"
